name: headheartpower
favicon: null
layout_spectrum: 0.74818
typography_spectrum: 0.64811
title: 'Head, Heart & Power Blog'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#dddbce'
    - '#b9b7aa'
    - '#656469'
    - '#48474c'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
