name: headheartpower
favicon: null
layout_spectrum: 0.74818
typography_spectrum: 0.64811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252523'
    - '#fde4b2'
    - '#4c513c'
    - '#b44a29'
    - '#e1925f'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
